# palinrome=
# 121=121
# num=int(input("Enter a number:"))
# temp=num
# rev=0
# while temp>0:
#   digit=temp%10
#   rev=rev*10+digit
#   temp//=10
# if num==rev:
#   print(num,"is a palindrome")
# else:
#   print(num,"is not a palindrome")

# class Solution:
#   def isPalindrome(self, num):
#     temp=num
#     rev=0
#     while temp>0:
#       digit=temp%10
#       rev=rev*10+digit
#       temp//=10
#     if num==rev:
#       return True
#     else:
#       return False
# s=Solution()
# num=int(input("Enter a number:"))
# print(s.isPalindrome(num))