# -----10/06/26-----
# print the outputs
# print("hello!jashwanth")
# name=input()
# print(name)
# n=int(map(input()))
# print(n)
# s=int(list(map(input())))
# name = "jashwanth kumar reddy kondasani"
# age = 21
# print(f"hello my name is {name},my age isf{age}.")


# variables
# num = 21
# print(num)
# name = "jash"
# print(name)
# f = 2.2
# print(f)
# name = input()
# greeting = "Hello"
# print(greeting+","+name+"!"
# a = 10
# b = 233.55
# product = a*b
# print(f"{product:.2f}")


# casting
# explicit
# num = 5.5
# num = int(5.5)
# print(num)


# num = int(3.7)  # num will be 3


# num = float(5)  # num will be 5.0
# str(): Converts a value to a string.

# Example:
# text = str(100)  # text will be '100'
# list(): Converts a value to a list.

# Example:
# my_list = list((1, 2, 3))  # my_list will be [1, 2, 3]
# tuple(): Converts a value to a tuple.

# Example:
# my_tuple = tuple([1, 2, 3])  # my_tuple will be (1, 2, 3)

# implicit
# num1 = 5.3
# num2 = 10
# result = num1 + num2
# num = 11
# res = num+4.4
# print(res)
# name = "jashwanth"
# age = 21
# print(f"hello my name is {name}, my age is {age}.")
# length = 10
# width = 5
# print(area := length * width  )
