# -----10/06/26-----
# print the outputs
# print("hello!jashwanth")
# name=input()
# print(name)
# n=int(map(input()))
# print(n)
# s=int(list(map(input())))
# name = "jashwanth kumar reddy kondasani"
# age = 21
# print(f"hello my name is {name},my age isf{age}.")


# variables
# num = 21
# print(num)
# name = "jash"
# print(name)
# f = 2.2
# print(f)
# name = input()
# greeting = "Hello"
# print(greeting+","+name+"!"
# a = 10
# b = 233.55
# product = a*b
# print(f"{product:.2f}")


# casting
# explicit
# num = 5.5
# num = int(5.5)
# print(num)


# num = int(3.7)  # num will be 3


# num = float(5)  # num will be 5.0
# str(): Converts a value to a string.

# Example:
# text = str(100)  # text will be '100'
# list(): Converts a value to a list.

# Example:
# my_list = list((1, 2, 3))  # my_list will be [1, 2, 3]
# tuple(): Converts a value to a tuple.

# Example:
# my_tuple = tuple([1, 2, 3])  # my_tuple will be (1, 2, 3)

# implicit
# num1 = 5.3
# num2 = 10
# result = num1 + num2
# num = 11
# res = num+4.4
# print(res)
# name = "jashwanth"
# age = 21
# print(f"hello my name is {name}, my age is {age}.")
# length = 10
# width = 5
# print(area := length * width  )
# x=1000
# y=20
# print(x>y)
# for i in range(1,7):
#     if i==2:
#         break
#     print(i)
# name="jashwanth"
# print(len(name))
# if 10==10:
#   print("yes")
# for i in range(6):
#   print(i)
# numbers=[1,2,34,5,6,6]
# print(numbers[5])

# marks=[12,34,55,78,55]
# print(marks.pop(2))
# count=1
# while count<=5:
#     print("jai sri ram")
#     count+=1
# n=int(input("enter starting number:-"))
# m=int(input("enter ending number:-"))
# for i in range(n,m+1,2):
#   print(i)
# sum=0
# for i in range(1,100):
#     sum+=i
# print(sum)
# table=5
# for i in range(1,11):
#     print(f"{table} x {i} = {table*i}")
# count=0
# for i in range(1,200):
#   if i%7==0:
#     count+=1
# print(count)
# name="jashwanth"
# count=0
# for ch in name:
#   count+=1
# print(count)
# count=0
# name="jashwanth"
# vowels="aeiou"
# count=0
# for ch in name:
#   if ch in vowels:
#     count+=1
# print(count)
# name="KONDASANI JAShwanth kumar reddy"
# upper_count=0
# lower_count=0
# for ch in name:
#   if upper_count in name:
#      upper_count+=1
#   else:
#      lower_count+=1
# print("uppercase letters",upper_count)
# print("lowercase letters",lower_count)
# name="KondaSaniJashwanthKumarReddy"
# upper_count=0
# lower_count=0
# for ch in name:
#   if ch.isupper():
#     upper_count+=1
#   else:
#     lower_count+=1
# print("upperletters",upper_count)
# print("lower_count",lower_count)
# nums=[10,20,30,40,50]
# maximum=nums[0]
# for num in nums:
#    if num>maximum:
#       maximum=num
# print(maximum)
# nums=[1,2,4,66,3,1,0]
# minimum=nums[0]
# for num in nums:
#   if num<minimum:
#     minimum=num
# print(minimum)
# name="ammananna"
# print(name.upper())
# print(name.lower())
# print(name.title())
# name="123nanna"
# print(name.capitalize())  
# print(name.isalpha())
# print(name.isalnum())
# n=19
# count=0
# for i in range(1,n+1):
#   if n%i==0:
#     count+=1
# if count==2:
#   print("prime number")
# else:
#   print("not an prime number")
# fact=1
# def fact(n):
#   fact=1
#   for i in range(1,n+1):
#     fact=fact*i
#   return fact
# print(fact(5))
# def fact(n):
#   fact=1
#   for i in range(1,n+1):
#     fact=fact*i
#   print(fact)
# fact(5)
# n=123
# rev=0
# while n>0:
#   digit=n%10
#   rev=rev*10+digit
#   n//=10
# print(rev)
# n=13232367890
# largest=0
# while n>0:
#   digit=n%10
#   if digit>largest:
#     largest=digit
#   n//=10
# print(largest)
# a=12
# b=18

# gcd=1

# for i in range(1,min(a,b)+1):
#   if a%i==0 and b%i==0:
#     gcd=i
# print(gcd)
# def prime(n):
#   count=0
#   for i in range(1,n+1):
#     if n%i==0:
#       count+=1
#   if count==2:
#       print("prime number")
#   else:
#       print("not prime")
# prime(52)
# def sum(n):
#   sum=0
#   while n>0:
#     digit=n%10
#     sum+=digit
#     n//=10
#   print(sum)
# sum(552456543)
# def palindrome(n):
#   rev=0
#   orig=n
#   while n>0:
#     digit=n%10
#     rev=rev*10+digit
#     n//=10
#   if orig==rev:
#     print("palindrome")
#   else:
#     print("not an palindrome")
# palindrome(121)

# def largest(n):
#   largest=0
#   while n>0:
#     digit=n%10
#     if digit>largest:
#       largest=digit
#     n//=10
#   print(largest)
# largest(123459876)
# def largest():/
# nums=[1,3,4,5,6]
# max=num[0]
# for nums in range(len(nums)):
#   if nums[i]>nums[0]
#   nums[i]=max
# print(max)
# nums=[9,2,4,33,4552,0,78987654]
# largest=nums[0]
# for i in range(len(nums)):
#   if nums[i]>largest:
#    largest=nums[i]
# print(largest)
# def largest(nums):
#   largest=nums[0]
#   for i in range(len(nums)):
#     if nums[i]>largest:
#       largest=nums[i]
#   print(largest)
# largest([1,2,3,5,5,99992])

# nums=[1,23,45,67,89,100]
# total=0
# for i in nums:
#    total+=i
# print(total)
# print("jai sri ram")
# print("hello jash")
# name=int(input("enter your name:-"))
# name=input("enter your name man")
# n=12
# m=123
# print("n:-",n,"m",m)
# DATA TYPES
# a=11
# b="jash"
# c=1.23
# d=3+7j
# print(a,b,c,d)
# print(type(b))
a=3
b=4
# print(a+b)
# print(a-b)
# print(a*b)
# print(a//b)
# print(a%b)

# conditional statements
# a=10
# b=15
# if a>b:
#   print("a is big")
# else:
#   print("b is big")
# marks=60
# if marks>=90:
#   print("A  grade")
# elif  80<=marks<=90:
#   print("B grade")
# elif  70<=marks<=80:
#   print("C grade")
# elif  60<=marks<=70:
#   print("D grade")
# name="i love u"
# i=5
# while i>0:
#   print(name)
#   i-=1
# name="jashwanth"
# n=12
# while n>0:
#   print(name)
#   n-=1  
# n=14
# while n>0:
#   print(name)
#   n-=1
# n=5
# while n>0:
#   print("jashwanth")
#   n-=1
# n=5
# while n>0:
#   print(n)
#   n-=1
# n=0
# while n<5:
#   print(n)
#   n+=1
# n=1
# while n<=10:
#   print("jai sri ram")
#   n+=1
# for i in range(1,10):
#   print(i)
# nums=[1,2,3,4,5]
# for num in nums:
#   print(num)
# nums=[11,22,33,44,55]
# for i in nums:
#     print([i])
# a=9543
# b=11678
# c=3356
# if a>=b and b>=c:
#   print(" a is big")
# elif b>=c and b>=a:
#   print(" b is large")
# else:
#   print(" c is large")
# year=2012
# if (year%100!=0 and year%4==0) or (year%400==0):
#   print("leap year")
# else:
#   print("not an leap year")
# year=7799
# if(year%4==0 and year%100!=0) or (year%400==0):
#   print("it is leap year")
# else:
#   print("not an leap year")
# a=10
# b=11
# c=12
# if (a+b>c) and (b+c>a) and (c+a>b):
#   print("valid triangle")
# else:
#   print("not  a valid triangle")\
# a=1
# b=11
# c=31
# if a==b and b==c and c==a:
#   print("equilateral triangle")
# # elif a==b and b==c and c==a or a!=b or b!=c or c!=a
# elif a==b or b==c or c==a:
#   print("isocelos triangle")
# else:
#   print("scalane triangle")
# balance=int(input("enter the balance of amnmount:-"))
# amount=int(input("enter the with drawl amount"))
# remainingbalance=balance-amount
# if amount>0 and amount<=balance  :
#   print("transaction succesfull")
#   print("remainingbalance",remainingbalance)
# n=5
# for i in range(1,n+1):
#   print(i)
# n=5
# for i in range(n,0,-1):
#   print(i)
# for i in range(2,21,2):
#   print(i)
# for i in range(1,21,2):
#   print(i)
# table=5
# for i in range(1,11):
#   print(table,"*",i,"=",table*i)
# sum=0
# for i in range(1,6):
#   sum+=i
# print(sum)
# n=5
# fact=1
# for i in range(1,n+1):
#   fact=fact*i
# print(fact)
# n=123239988
# count=0
# while n>0:
#   n//=10
#   count+=1
# print(count)
# for i in range(1,1000):
#   count=0
#   for j in range(1, i+1):
#     if i%j==0:
#       count+=1
#   if count==2:
#     print(i)
# n=141
# original=n
# sum=0
# while n>0:
#   digit=n%10
#   sum=sum*10+digit
#   n//=10
# if original==sum:
#   print("palindrome")
# else:
#   print("not an palindrome")
#  armstrong umber
# n=154
# original=n
# sum=0
# while n>0:
#   digit=n%10
#   sum=sum+digit**3
#   n//=10
# if original==sum:
#   print("armstrong number")
# else:
#   print("not an armstrong number")
# n=int(input())
# arr=map(int,input().split())
# arr1=list(arr)
# arr1=list(set(arr1))
# arr1.sort()
# print(arr1[-2])
