# DATATYPES ARE CLASSIFIED INTO MAJORLY TWO TYPES
# NUM=INT,FLOAT,COMPLEX
# STR=CHAR,STRING

# FOR NUMBERS
# 1.INT
# 2.FLOAT
# 3.COMPLEX


# 1 INTEGER
# a = 10
# print(a)
# print(type(a))

# 2.float
# b = 1.54
# print(b)
# print(type(b))


# 3comples
# a = 10+77j
# print(a)
# print(type(a))


# sequence type
# 1.string
# 2.list
# 3.tuple
# 4.boolean

# 1.string
# n = "jashwanth kumar reddy"
# print(n)
# print(type(n))
print(type(10))

print(type(3.14))

print(type(True))

print(type("Python"))

print(type(None))